apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
spec:
  containers:
  - name: tomcat
    image: tomcat:latest
    env:
    - name: DB_HOST
      value: mysql-service
    - name: DB_PORT
      value: "3306"
    - name: DB_USERNAME
      value: root
    - name: DB_PASSWORD
      value: mysql
    ports:
    - containerPort: 8080
  restartPolicy: Mas
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
  - name: tomcat
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: mysql
    ports:
    - containerPort: 3306
  restartPolicy: Mas
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  type: ClusterIP
